
# import sys

# try:
#     a = 1/0
# except Exception as e:
#     print(e)
# print(sys.exc_info())

from src.logger.logging import logging

logging.info("this is my testing")
logging.info(" this my second testing")
# logging.info(" this my second testing")

# logging.info(" this my second testing")
# logging.info(" this my second testing")
# logging.info(" this my second testing")
